Score.create!([
  {name: "P.S. 015 Roberto Clemente", admin: "Irene Sanchez", level: nil, grade: "C"},
  {name: "P.S. 019 Asher Levy", admin: "Jacqueline Flanagan", level: nil, grade: "B"},
  {name: "P.S. 020 Anna Silver", admin: "James Lee", level: nil, grade: "B"},
  {name: "P.S. 034 Franklin D. Roosevelt", admin: "Joyce Stallings Harte", level: nil, grade: "C"},
  {name: "P.S. 063 William McKinley", admin: "Darlene Despeignes", level: nil, grade: "B"},
  {name: "P.S. 064 Robert Simon", admin: "Marlon L. Hosang", level: nil, grade: "C"},
  {name: "P.S. 110 Florence Nightingale", admin: "Karen Feuer", level: nil, grade: "C"},
  {name: "P.S. 134 Henrietta Szold", admin: "Loretta Caputo", level: nil, grade: "C"},
  {name: "P.S. 137 John L. Bernstein", admin: "Melissa Rodriguez", level: nil, grade: "F"},
  {name: "P.S. 140 Nathan Straus", admin: "Esteban Barrientos", level: nil, grade: "D"},
  {name: "P.S. 142 Amalia Castro", admin: "Rhonda Levy", level: nil, grade: "C"},
  {name: "P.S. 184m Shuang Wen", admin: "Ling Ling Chou", level: nil, grade: "A"},
  {name: "P.S. 188 The Island School", admin: "Mary Pree", level: nil, grade: "A"},
  {name: "Henry Street School for International Studies", admin: "Erin Balet", level: nil, grade: "C"},
  {name: "Henry Street School for International Studies", admin: "Erin Balet", level: nil, grade: "C"},
  {name: "Technology, Arts, and Sciences Studio", admin: "George Morgan", level: nil, grade: "B"},
  {name: "The East Village Community School", admin: "Robin Williams", level: nil, grade: "C"},
  {name: "University Neighborhood Middle School", admin: "Laura Peynado", level: nil, grade: "C"},
  {name: "Collaborative Academy of Science, Technology, & La", admin: "Judith De Los Santos", level: nil, grade: "B"},
  {name: "The Children's Workshop School", admin: "Maria Velez Clarke", level: nil, grade: "B"},
  {name: "Neighborhood School", admin: "Milo Novelo", level: nil, grade: "C"},
  {name: "Earth School", admin: "Alison Gail Hazut", level: nil, grade: "C"},
  {name: "School for Global Leaders", admin: "Carry Chan", level: nil, grade: "B"},
  {name: "University Neighborhood High School", admin: "Elizabeth Collins", level: nil, grade: "C"},
  {name: "East Side Community School", admin: "Mark Federman", level: nil, grade: "A"},
  {name: "East Side Community School", admin: "Mark Federman", level: nil, grade: "A"},
  {name: "Forsyth Satellite Academy", admin: "Ingrid Roberts Haynes", level: nil, grade: nil},
  {name: "Marta Valle High School", admin: "Mimi Fortunato", level: nil, grade: "C"},
  {name: "Lower East Side Preparatory High School", admin: "Martha Polin", level: nil, grade: "A"},
  {name: "New Explorations into Science, Technology and Math", admin: "Dr. Olga Livanis", level: nil, grade: "A"},
  {name: "New Explorations into Science, Technology and Math High School", admin: "Dr. Olga Livanis", level: nil, grade: "A"},
  {name: "Cascades High School", admin: "Paul Rotondo", level: nil, grade: "A"},
  {name: "Bard High School Early College", admin: "Michael Lerner", level: nil, grade: "B"},
  {name: "Tompkins Square Middle School", admin: "Sonhando Estwick", level: nil, grade: "B"},
  {name: "P.S. 001 Alfred E. Smith", admin: "Amy Hom", level: nil, grade: "B"},
  {name: "P.S. 002 Meyer London", admin: "Brett Gustafson", level: nil, grade: "A"},
  {name: "P.S. 003 Charrette School", admin: "Lisa Siegman", level: nil, grade: "C"},
  {name: "P.S. 006 Lillie D. Blake", admin: "Lauren Fontana", level: nil, grade: "A"},
  {name: "P.S. 011 William T. Harris", admin: "Robert Bender", level: nil, grade: "A"},
  {name: "P.S. 033 Chelsea Prep", admin: "Linore Lindy", level: nil, grade: "B"},
  {name: "P.S. 040 Augustus Saint-Gaudens", admin: "Susan Felder", level: nil, grade: "A"},
  {name: "P.S. 041 Greenwich Village", admin: "Kelly Shannon", level: nil, grade: "A"},
  {name: "P.S. 042 Benjamin Altman", admin: "Rosa Casiello O'Day", level: nil, grade: "A"},
  {name: "47 The American Sign Language and English Secondary School", admin: "Watfa A. Shama", level: nil, grade: "C"},
  {name: "P.S. 051 Elias Howe", admin: "Nancy Sing Bock", level: nil, grade: "B"},
  {name: "P.S. 059 Beekman Hill International", admin: "Adele Schroeter", level: nil, grade: "A"},
  {name: "P.S. 77 Lower Lab School", admin: "Mara Ratesic Koetke", level: nil, grade: "A"},
  {name: "P.S. 89", admin: "Veronica Najjar", level: nil, grade: "B"},
  {name: "J.H.S. 104 Simon Baruch", admin: "Rosemarie Gaetani", level: nil, grade: "B"},
  {name: "P.S. 111 Adolph S. Ochs", admin: "Irma Medina", level: nil, grade: "C"}
])
